import { useState } from "react";
import { useQuery } from "convex/react";
import { api } from "convex-api";

type Tab = "overview" | "comments" | "reactions" | "votes" | "users";

function formatTime(ts: number) {
  return new Date(ts).toLocaleString("sr-RS", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function timeAgo(ts: number) {
  const diff = Date.now() - ts;
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

function Stat({ label, value }: { label: string; value: number | string }) {
  return (
    <div style={styles.statCard}>
      <div style={styles.statValue}>{value}</div>
      <div style={styles.statLabel}>{label}</div>
    </div>
  );
}

function Overview() {
  const stats = useQuery(api.admin.getStats);
  if (!stats) return <p>Loading...</p>;

  return (
    <div>
      <div style={styles.statsGrid}>
        <Stat label="Total Comments" value={stats.comments} />
        <Stat label="Auto-generated" value={stats.autoComments} />
        <Stat label="Verified (signed-in)" value={stats.verifiedComments} />
        <Stat label="Users" value={stats.users} />
        <Stat label="Listings" value={stats.listings} />
        <Stat label="Deleted Listings" value={stats.deletedListings} />
        <Stat label="Total Votes" value={stats.votes} />
        <Stat label="Upvotes" value={stats.upvotes} />
        <Stat label="Downvotes" value={stats.downvotes} />
        <Stat label="Total Reactions" value={stats.reactions} />
        <Stat label="Price Reactions" value={stats.priceReactions} />
        <Stat label="General Reactions" value={stats.generalReactions} />
        <Stat label="Notifications" value={stats.notifications} />
        <Stat label="Unread Notifs" value={stats.unreadNotifications} />
      </div>
    </div>
  );
}

function Comments() {
  const comments = useQuery(api.admin.getLatestComments);
  if (!comments) return <p>Loading...</p>;

  return (
    <table style={styles.table}>
      <thead>
        <tr>
          <th style={styles.th}>Time</th>
          <th style={styles.th}>User</th>
          <th style={styles.th}>Comment</th>
          <th style={styles.th}>Listing</th>
          <th style={styles.th}>Flags</th>
        </tr>
      </thead>
      <tbody>
        {comments.map((c) => (
          <tr key={c._id} style={styles.tr}>
            <td style={styles.td} title={formatTime(c.createdAt)}>
              {timeAgo(c.createdAt)}
            </td>
            <td style={styles.td}>{c.username}</td>
            <td style={{ ...styles.td, maxWidth: 400 }}>
              {c.text.length > 120 ? c.text.slice(0, 120) + "…" : c.text}
            </td>
            <td style={styles.td}>
              {c.listingUrl ? (
                <a href={c.listingUrl} target="_blank" rel="noreferrer" style={styles.link}>
                  {c.listingTitle || c.listingId}
                </a>
              ) : (
                c.listingId
              )}
            </td>
            <td style={styles.td}>
              {c.isReply && <span style={styles.badge}>reply</span>}
              {c.isAutoGenerated && <span style={{ ...styles.badge, background: "#f59e0b" }}>auto</span>}
              {c.isVerified && <span style={{ ...styles.badge, background: "#10b981" }}>verified</span>}
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function Reactions() {
  const reactions = useQuery(api.admin.getLatestReactions);
  if (!reactions) return <p>Loading...</p>;

  return (
    <table style={styles.table}>
      <thead>
        <tr>
          <th style={styles.th}>Time</th>
          <th style={styles.th}>Emoji</th>
          <th style={styles.th}>Category</th>
          <th style={styles.th}>Target Type</th>
          <th style={styles.th}>Target</th>
          <th style={styles.th}>Reactor</th>
        </tr>
      </thead>
      <tbody>
        {reactions.map((r) => (
          <tr key={r._id} style={styles.tr}>
            <td style={styles.td}>{timeAgo(r._creationTime)}</td>
            <td style={{ ...styles.td, fontSize: 20 }}>{r.emoji}</td>
            <td style={styles.td}>
              <span style={{ ...styles.badge, background: r.category === "price" ? "#f59e0b" : "#6366f1" }}>
                {r.category}
              </span>
            </td>
            <td style={styles.td}>{r.targetType}</td>
            <td style={{ ...styles.td, maxWidth: 300 }}>{r.targetLabel}</td>
            <td style={styles.td}>
              <code style={styles.code}>{r.reactorId.slice(0, 12)}…</code>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function Votes() {
  const votes = useQuery(api.admin.getLatestVotes);
  if (!votes) return <p>Loading...</p>;

  return (
    <table style={styles.table}>
      <thead>
        <tr>
          <th style={styles.th}>Time</th>
          <th style={styles.th}>Direction</th>
          <th style={styles.th}>Comment</th>
          <th style={styles.th}>Comment Author</th>
          <th style={styles.th}>Voter</th>
        </tr>
      </thead>
      <tbody>
        {votes.map((v) => (
          <tr key={v._id} style={styles.tr}>
            <td style={styles.td}>{timeAgo(v._creationTime)}</td>
            <td style={styles.td}>
              <span style={{ ...styles.badge, background: v.direction === "up" ? "#10b981" : "#ef4444" }}>
                {v.direction === "up" ? "↑ up" : "↓ down"}
              </span>
            </td>
            <td style={{ ...styles.td, maxWidth: 300 }}>{v.commentText ?? "—"}</td>
            <td style={styles.td}>{v.commentUsername ?? "—"}</td>
            <td style={styles.td}>
              <code style={styles.code}>{v.voterId.slice(0, 12)}…</code>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function Users() {
  const users = useQuery(api.admin.getUsers);
  if (!users) return <p>Loading...</p>;

  return (
    <table style={styles.table}>
      <thead>
        <tr>
          <th style={styles.th}>Name</th>
          <th style={styles.th}>Email</th>
          <th style={styles.th}>Comments</th>
          <th style={styles.th}>Upvotes Recv</th>
          <th style={styles.th}>Created</th>
          <th style={styles.th}>Last Seen</th>
          <th style={styles.th}>Flags</th>
        </tr>
      </thead>
      <tbody>
        {users.map((u) => (
          <tr key={u._id} style={styles.tr}>
            <td style={styles.td}>{u.displayName}</td>
            <td style={styles.td}>{u.email}</td>
            <td style={styles.td}>{u.commentCount}</td>
            <td style={styles.td}>{u.upvotesReceived}</td>
            <td style={styles.td}>{formatTime(u.createdAt)}</td>
            <td style={styles.td} title={formatTime(u.lastSeenAt)}>
              {timeAgo(u.lastSeenAt)}
            </td>
            <td style={styles.td}>
              {u.isCustomName && <span style={styles.badge}>custom name</span>}
              {u.emailNotifications && (
                <span style={{ ...styles.badge, background: "#10b981" }}>email on</span>
              )}
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

const TABS: { key: Tab; label: string }[] = [
  { key: "overview", label: "Overview" },
  { key: "comments", label: "Comments" },
  { key: "reactions", label: "Reactions" },
  { key: "votes", label: "Votes" },
  { key: "users", label: "Users" },
];

export default function App() {
  const [tab, setTab] = useState<Tab>("overview");

  return (
    <div style={styles.container}>
      <h1 style={styles.title}>Polovni Komentari Admin</h1>
      <nav style={styles.nav}>
        {TABS.map((t) => (
          <button
            key={t.key}
            onClick={() => setTab(t.key)}
            style={tab === t.key ? { ...styles.tabBtn, ...styles.tabActive } : styles.tabBtn}
          >
            {t.label}
          </button>
        ))}
      </nav>
      <div style={styles.content}>
        {tab === "overview" && <Overview />}
        {tab === "comments" && <Comments />}
        {tab === "reactions" && <Reactions />}
        {tab === "votes" && <Votes />}
        {tab === "users" && <Users />}
      </div>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  container: {
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    maxWidth: 1200,
    margin: "0 auto",
    padding: "24px 16px",
    color: "#e2e8f0",
    background: "#0f172a",
    minHeight: "100vh",
  },
  title: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 16,
    color: "#f8fafc",
  },
  nav: {
    display: "flex",
    gap: 4,
    marginBottom: 24,
    borderBottom: "1px solid #334155",
    paddingBottom: 8,
  },
  tabBtn: {
    padding: "8px 16px",
    border: "none",
    background: "transparent",
    color: "#94a3b8",
    cursor: "pointer",
    borderRadius: "6px 6px 0 0",
    fontSize: 14,
    fontWeight: 500,
  },
  tabActive: {
    background: "#1e293b",
    color: "#f8fafc",
  },
  content: {
    background: "#1e293b",
    borderRadius: 8,
    padding: 20,
    overflowX: "auto",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))",
    gap: 12,
  },
  statCard: {
    background: "#0f172a",
    borderRadius: 8,
    padding: 16,
    textAlign: "center",
  },
  statValue: {
    fontSize: 28,
    fontWeight: 700,
    color: "#38bdf8",
  },
  statLabel: {
    fontSize: 12,
    color: "#94a3b8",
    marginTop: 4,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 13,
  },
  th: {
    textAlign: "left",
    padding: "8px 12px",
    borderBottom: "1px solid #334155",
    color: "#94a3b8",
    fontWeight: 600,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  tr: {
    borderBottom: "1px solid #1e293b",
  },
  td: {
    padding: "8px 12px",
    verticalAlign: "top",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  badge: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: 9999,
    fontSize: 11,
    fontWeight: 600,
    background: "#6366f1",
    color: "#fff",
    marginRight: 4,
  },
  link: {
    color: "#38bdf8",
    textDecoration: "none",
  },
  code: {
    fontFamily: "monospace",
    fontSize: 12,
    color: "#94a3b8",
  },
};
