import React from "react";
import { createRoot } from "react-dom/client";
import { extractListingId } from "../utils/listingId";
import { extractListingInfo } from "../utils/listingInfo";
import { getOrCreateAnonymousId } from "../utils/anonymousId";
import { getOrCreateUsername } from "../utils/username";
import App from "../components/App";
import styles from "./shadow.css?inline";

function main() {
  const listingId = extractListingId(window.location.href);
  const listingInfo = listingId ? extractListingInfo() : null;

  const anonymousId = getOrCreateAnonymousId();
  const {
    username: initialUsername,
    isAutoGenerated: initialIsAutoGenerated,
  } = getOrCreateUsername();

  const host = document.createElement("div");
  host.id = "pa-comments-host";
  document.body.appendChild(host);

  const shadow = host.attachShadow({ mode: "open" });

  const style = document.createElement("style");
  style.textContent = styles;
  shadow.appendChild(style);

  const portalTarget = document.createElement("div");
  portalTarget.style.pointerEvents = "none";
  shadow.appendChild(portalTarget);

  const container = document.createElement("div");
  shadow.appendChild(container);

  const hostStyle = document.createElement("style");
  hostStyle.textContent =
    "#pa-comments-host { position: relative; z-index: 2147483647; }";
  document.head.appendChild(hostStyle);

  createRoot(container).render(
    <React.StrictMode>
      <App
        listingId={listingId}
        anonymousId={anonymousId}
        portalContainer={portalTarget}
        initialUsername={initialUsername}
        initialIsAutoGenerated={initialIsAutoGenerated}
        listingInfo={listingInfo}
      />
    </React.StrictMode>
  );
}

main();
