const CAR_BRANDS = [
  "Golf", "Punto", "Pezo", "Astra", "Jugo", "Stojadin", "Fica", "Yugo",
  "Clio", "Megane", "Octavia", "Fabia", "Polo", "Corsa", "Leon", "Ibiza",
  "Tipo", "Brava", "Uno", "Kadett", "Lada", "Niva", "Zastava", "Skala", "Koral",
];

export function generateRandomUsername(): string {
  const brand = CAR_BRANDS[Math.floor(Math.random() * CAR_BRANDS.length)];
  const num = Math.floor(Math.random() * 900 + 100); // 100-999
  return `${brand}${num}`;
}

const USERNAME_KEY = "paCommentsUsername";
const AUTO_GENERATED_KEY = "paCommentsUsernameAutoGenerated";

export interface StoredUsername {
  username: string;
  isAutoGenerated: boolean;
}

export function getOrCreateUsername(): StoredUsername {
  const stored = localStorage.getItem(USERNAME_KEY);
  if (stored) {
    return {
      username: stored,
      isAutoGenerated: localStorage.getItem(AUTO_GENERATED_KEY) !== "false",
    };
  }

  const username = generateRandomUsername();
  localStorage.setItem(USERNAME_KEY, username);
  localStorage.setItem(AUTO_GENERATED_KEY, "true");
  return { username, isAutoGenerated: true };
}

export function saveUsername(username: string, isAutoGenerated: boolean): void {
  localStorage.setItem(USERNAME_KEY, username);
  localStorage.setItem(AUTO_GENERATED_KEY, String(isAutoGenerated));
}
