import { query } from "./_generated/server";

export const getStats = query({
  args: {},
  handler: async (ctx) => {
    const [comments, votes, reactions, users, listings, notifications] =
      await Promise.all([
        ctx.db.query("comments").collect(),
        ctx.db.query("votes").collect(),
        ctx.db.query("reactions").collect(),
        ctx.db.query("users").collect(),
        ctx.db.query("listings").collect(),
        ctx.db.query("notifications").collect(),
      ]);

    const autoComments = comments.filter((c) => c.isAutoGenerated).length;
    const verifiedComments = comments.filter((c) => c.verifiedAt).length;
    const upvotes = votes.filter((v) => v.direction === "up").length;
    const downvotes = votes.filter((v) => v.direction === "down").length;
    const priceReactions = reactions.filter((r) => r.category === "price").length;
    const generalReactions = reactions.filter((r) => r.category === "general").length;
    const deletedListings = listings.filter((l) => l.isDeleted).length;
    const unreadNotifications = notifications.filter((n) => !n.read).length;

    return {
      comments: comments.length,
      autoComments,
      verifiedComments,
      votes: votes.length,
      upvotes,
      downvotes,
      reactions: reactions.length,
      priceReactions,
      generalReactions,
      users: users.length,
      listings: listings.length,
      deletedListings,
      notifications: notifications.length,
      unreadNotifications,
    };
  },
});

export const getLatestComments = query({
  args: {},
  handler: async (ctx) => {
    const comments = await ctx.db
      .query("comments")
      .withIndex("by_createdAt")
      .order("desc")
      .take(100);

    return Promise.all(
      comments.map(async (c) => {
        const listing = await ctx.db
          .query("listings")
          .withIndex("by_listingId", (q) => q.eq("listingId", c.listingId))
          .first();
        return {
          _id: c._id,
          _creationTime: c._creationTime,
          listingId: c.listingId,
          text: c.text,
          username: c.username,
          createdAt: c.createdAt,
          isAutoGenerated: c.isAutoGenerated,
          isVerified: !!c.verifiedAt,
          isReply: !!c.parentId,
          listingTitle: listing?.title ?? null,
          listingUrl: listing?.url ?? null,
        };
      })
    );
  },
});

export const getLatestReactions = query({
  args: {},
  handler: async (ctx) => {
    const reactions = await ctx.db
      .query("reactions")
      .order("desc")
      .take(100);

    return Promise.all(
      reactions.map(async (r) => {
        let targetLabel = r.targetId;
        if (r.targetType === "listing") {
          const listing = await ctx.db
            .query("listings")
            .withIndex("by_listingId", (q) => q.eq("listingId", r.targetId))
            .first();
          if (listing) targetLabel = listing.title;
        } else {
          const comment = await ctx.db.get(r.targetId as any);
          if (comment && "text" in comment) {
            targetLabel = (comment.text as string).slice(0, 60);
          }
        }
        return {
          _id: r._id,
          _creationTime: r._creationTime,
          targetType: r.targetType,
          targetId: r.targetId,
          targetLabel,
          emoji: r.emoji,
          category: r.category,
          reactorId: r.reactorId,
        };
      })
    );
  },
});

export const getLatestVotes = query({
  args: {},
  handler: async (ctx) => {
    const votes = await ctx.db.query("votes").order("desc").take(100);

    return Promise.all(
      votes.map(async (v) => {
        const comment = await ctx.db.get(v.commentId);
        return {
          _id: v._id,
          _creationTime: v._creationTime,
          direction: v.direction,
          voterId: v.voterId,
          commentId: v.commentId,
          commentText: comment?.text?.slice(0, 60) ?? null,
          commentUsername: comment?.username ?? null,
        };
      })
    );
  },
});

export const getUsers = query({
  args: {},
  handler: async (ctx) => {
    const users = await ctx.db.query("users").collect();
    return users
      .sort((a, b) => b.lastSeenAt - a.lastSeenAt)
      .map((u) => ({
        _id: u._id,
        displayName: u.displayName,
        email: u.email,
        isCustomName: u.isCustomName,
        createdAt: u.createdAt,
        lastSeenAt: u.lastSeenAt,
        emailNotifications: u.emailNotifications,
        commentCount: u.commentCount ?? 0,
        upvotesReceived: u.upvotesReceived ?? 0,
      }));
  },
});
