import { v } from "convex/values";
import { query, mutation } from "./_generated/server";
import { Id } from "./_generated/dataModel";
import { createNotificationsForReplyHelper } from "./notifications";

export const getComments = query({
  args: { listingId: v.string(), reactorId: v.optional(v.string()) },
  handler: async (ctx, { listingId, reactorId }) => {
    const comments = await ctx.db
      .query("comments")
      .withIndex("by_listing", (q) => q.eq("listingId", listingId))
      .collect();

    const withScores = await Promise.all(
      comments.map(async (comment) => {
        const votes = await ctx.db
          .query("votes")
          .withIndex("by_comment", (q) => q.eq("commentId", comment._id))
          .collect();
        const score = votes.reduce(
          (acc, v) => acc + (v.direction === "up" ? 1 : -1),
          0
        );

        const commentReactions = await ctx.db
          .query("reactions")
          .withIndex("by_target", (q) =>
            q.eq("targetType", "comment").eq("targetId", comment._id)
          )
          .collect();

        const countsMap = new Map<string, number>();
        for (const r of commentReactions) {
          countsMap.set(r.emoji, (countsMap.get(r.emoji) ?? 0) + 1);
        }
        const reactions = Array.from(countsMap.entries()).map(([emoji, count]) => ({
          emoji,
          count,
        }));

        const myReactions = reactorId
          ? commentReactions.filter((r) => r.reactorId === reactorId).map((r) => r.emoji)
          : [];

        return { ...comment, score, reactions, myReactions, isVerified: !!comment.userId };
      })
    );

    // Build lookup map for walking parent chains
    const byId = new Map(withScores.map((c) => [c._id, c]));

    // Find root ancestor by walking up parentId chain
    function findRoot(commentId: Id<"comments">): Id<"comments"> {
      let current = commentId;
      for (let i = 0; i < 100; i++) {
        const c = byId.get(current);
        if (!c || !c.parentId) return current;
        current = c.parentId;
      }
      return current;
    }

    const topLevel = withScores
      .filter((c) => !c.parentId)
      .sort((a, b) => b.score - a.score);

    // Group all non-root comments under their root ancestor
    const repliesByRoot = new Map<Id<"comments">, typeof withScores>();
    for (const c of withScores) {
      if (c.parentId) {
        const rootId = findRoot(c._id);
        if (!repliesByRoot.has(rootId)) repliesByRoot.set(rootId, []);
        repliesByRoot.get(rootId)!.push(c);
      }
    }
    // Sort replies chronologically
    for (const replies of repliesByRoot.values()) {
      replies.sort((a, b) => a.createdAt - b.createdAt);
    }

    return topLevel.map((c) => ({
      ...c,
      replies: (repliesByRoot.get(c._id) ?? []).map((r) => {
        // Add replyingTo when direct parent is not the root
        const directParent = r.parentId ? byId.get(r.parentId) : undefined;
        const isDirectChildOfRoot = r.parentId === c._id;
        return {
          ...r,
          replyingTo:
            !isDirectChildOfRoot && directParent
              ? { username: directParent.username, commentId: directParent._id }
              : undefined,
        };
      }),
    }));
  },
});

export const postComment = mutation({
  args: {
    listingId: v.string(),
    text: v.string(),
    authorId: v.string(),
    parentId: v.optional(v.id("comments")),
    username: v.string(),
    isAutoGenerated: v.boolean(),
    userId: v.optional(v.id("users")),
  },
  handler: async (ctx, { listingId, text, authorId, parentId, username, isAutoGenerated, userId }) => {
    const trimmed = text.trim();
    if (trimmed.length === 0) throw new Error("Comment cannot be empty");
    if (trimmed.length > 1000) throw new Error("Comment too long");

    if (parentId) {
      const parent = await ctx.db.get(parentId);
      if (!parent) throw new Error("Parent comment not found");
      if (parent.listingId !== listingId)
        throw new Error("Parent belongs to different listing");
    }

    const commentId = await ctx.db.insert("comments", {
      listingId,
      authorId,
      text: trimmed,
      createdAt: Date.now(),
      username,
      isAutoGenerated,
      ...(parentId ? { parentId } : {}),
      ...(userId ? { userId } : {}),
    });

    if (parentId) {
      await createNotificationsForReplyHelper(ctx, {
        commentId,
        parentId,
        listingId,
        authorName: username,
        authorId,
      });
    }

    return commentId;
  },
});

export const seedComment = mutation({
  args: {
    listingId: v.string(),
    text: v.string(),
    authorId: v.string(),
    parentId: v.optional(v.id("comments")),
    username: v.string(),
    isAutoGenerated: v.boolean(),
    createdAt: v.number(),
  },
  handler: async (ctx, args) => {
    return ctx.db.insert("comments", {
      listingId: args.listingId,
      authorId: args.authorId,
      text: args.text,
      createdAt: args.createdAt,
      username: args.username,
      isAutoGenerated: args.isAutoGenerated,
      ...(args.parentId ? { parentId: args.parentId } : {}),
    });
  },
});

export const findListingsWithoutComments = query({
  args: { listingIds: v.array(v.string()) },
  handler: async (ctx, { listingIds }) => {
    const result: string[] = [];
    for (const listingId of listingIds) {
      const comment = await ctx.db
        .query("comments")
        .withIndex("by_listing", (q) => q.eq("listingId", listingId))
        .first();
      if (!comment) result.push(listingId);
    }
    return result;
  },
});

export const getLatestComments = query({
  args: {},
  handler: async (ctx) => {
    const comments = await ctx.db
      .query("comments")
      .withIndex("by_createdAt")
      .order("desc")
      .take(50);

    const withListings = await Promise.all(
      comments.map(async (comment) => {
        const listing = await ctx.db
          .query("listings")
          .withIndex("by_listingId", (q) =>
            q.eq("listingId", comment.listingId)
          )
          .first();

        const replies = comment.parentId
          ? []
          : await ctx.db
              .query("comments")
              .withIndex("by_parent", (q) => q.eq("parentId", comment._id))
              .collect();

        const parent = comment.parentId
          ? await ctx.db.get(comment.parentId)
          : null;

        return {
          _id: comment._id,
          text: comment.text,
          username: comment.username,
          isAutoGenerated: comment.isAutoGenerated,
          createdAt: comment.createdAt,
          replyingToUsername: parent ? parent.username : undefined,
          replies: replies.map((r) => ({
            _id: r._id,
            text: r.text,
            username: r.username,
            isAutoGenerated: r.isAutoGenerated,
            createdAt: r.createdAt,
          })),
          listing: listing
            ? {
                title: listing.title,
                price: listing.price,
                imageUrl: listing.imageUrl,
                url: listing.url,
                isDeleted: listing.isDeleted ?? false,
              }
            : null,
        };
      })
    );

    return withListings;
  },
});
