import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  comments: defineTable({
    listingId: v.string(),
    authorId: v.string(),
    text: v.string(),
    createdAt: v.number(),
    parentId: v.optional(v.id("comments")),
    username: v.string(),
    isAutoGenerated: v.boolean(),
    userId: v.optional(v.id("users")),
    verifiedAt: v.optional(v.number()),
  })
    .index("by_listing", ["listingId"])
    .index("by_parent", ["parentId"])
    .index("by_createdAt", ["createdAt"])
    .index("by_authorId", ["authorId"]),

  votes: defineTable({
    commentId: v.id("comments"),
    voterId: v.string(),
    direction: v.union(v.literal("up"), v.literal("down")),
  })
    .index("by_comment", ["commentId"])
    .index("by_comment_voter", ["commentId", "voterId"]),

  listings: defineTable({
    listingId: v.string(),
    title: v.string(),
    price: v.string(),
    imageUrl: v.string(),
    url: v.string(),
    isDeleted: v.optional(v.boolean()),
  }).index("by_listingId", ["listingId"]),

  reactions: defineTable({
    targetType: v.union(v.literal("listing"), v.literal("comment")),
    targetId: v.string(),
    reactorId: v.string(),
    emoji: v.string(),
    category: v.union(v.literal("price"), v.literal("general")),
  })
    .index("by_target", ["targetType", "targetId"])
    .index("by_target_reactor", ["targetType", "targetId", "reactorId"]),

  vinChecks: defineTable({
    vin: v.string(),
    found: v.boolean(),
    statusLines: v.array(v.string()),
    checkedAt: v.number(),
  })
    .index("by_vin", ["vin"]),

  users: defineTable({
    googleId: v.string(),
    email: v.string(),
    firstName: v.string(),
    displayName: v.string(),
    isCustomName: v.boolean(),
    anonymousId: v.string(),
    createdAt: v.number(),
    lastSeenAt: v.number(),
    emailNotifications: v.boolean(),
    sessionToken: v.optional(v.string()),
    unsubscribeToken: v.optional(v.string()),
    commentCount: v.optional(v.number()),
    upvotesReceived: v.optional(v.number()),
  })
    .index("by_googleId", ["googleId"])
    .index("by_anonymousId", ["anonymousId"])
    .index("by_email", ["email"]),

  notifications: defineTable({
    userId: v.id("users"),
    type: v.literal("reply"),
    commentId: v.id("comments"),
    triggerAuthorName: v.string(),
    listingId: v.string(),
    read: v.boolean(),
    emailSent: v.boolean(),
    createdAt: v.number(),
  })
    .index("by_userId_read", ["userId", "read"])
    .index("by_userId_createdAt", ["userId", "createdAt"]),
});
