import { useState } from "react";
import { ThumbsUp, ThumbsDown, MessageSquare, User, ShieldCheck } from "lucide-react";
import { Id } from "../../convex/_generated/dataModel";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { formatTimeAgo } from "../utils/formatTimeAgo";
import { CommentReactions } from "./CommentReactions";
import { trackEvent } from "../utils/tracking";

export interface Comment {
  _id: Id<"comments">;
  text: string;
  score: number;
  createdAt: number;
  authorId: string;
  parentId?: Id<"comments">;
  replies?: Comment[];
  username: string;
  isAutoGenerated: boolean;
  reactions?: Array<{emoji: string; count: number}>;
  myReactions?: string[];
  replyingTo?: { username: string; commentId: Id<"comments"> };
  isVerified?: boolean;
}

interface Props {
  comment: Comment;
  currentVotes: Record<string, "up" | "down">;
  onVote: (commentId: string, direction: "up" | "down") => void;
  onReply: (parentId: string, text: string) => Promise<void>;
  onReact: (targetType: "listing" | "comment", targetId: string, emoji: string, category: "price" | "general") => void;
  anonymousId: string;
}

export function CommentItem({ comment, currentVotes, onVote, onReply, onReact, anonymousId }: Props) {
  const [showReplyForm, setShowReplyForm] = useState(false);
  const [replyText, setReplyText] = useState("");
  const [posting, setPosting] = useState(false);
  const timeAgo = formatTimeAgo(comment.createdAt);
  const isOwn = comment.authorId === anonymousId;
  const currentVote = currentVotes[comment._id] ?? null;

  async function handleReplySubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!replyText.trim()) return;
    setPosting(true);
    try {
      await onReply(comment._id, replyText);
      setReplyText("");
      setShowReplyForm(false);
    } finally {
      setPosting(false);
    }
  }

  return (
    <div>
      <div className="flex gap-3 py-3 border-b border-gray-100 last:border-0">
        {/* Avatar */}
        <div className="shrink-0 w-9 h-9 rounded-full bg-gray-100 flex items-center justify-center">
          <User className="h-[17px] w-[17px] text-gray-400" />
        </div>

        {/* Content */}
        <div className="flex-1 min-w-0">
          <p className={`text-[12px] font-medium mb-0.5 ${comment.isAutoGenerated ? "italic text-gray-400" : "text-gray-600"}`}>
            {comment.username}
            {comment.isVerified && (
              <span className="ml-0.5 inline-flex align-middle relative group cursor-default">
                <ShieldCheck className="h-4 w-4 text-orange-400" />
                <span className="absolute bottom-full left-1/2 -translate-x-1/2 mb-1 px-2 py-0.5 text-[10px] text-white bg-gray-800 rounded whitespace-nowrap opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none">
                  Prijavljen korisnik
                </span>
              </span>
            )}
          </p>
          <div className="flex justify-between items-center gap-2">
            <p className="text-[14px] text-gray-800 break-words leading-snug flex-1 min-w-0">
              {comment.replyingTo && (
                <span className="font-semibold text-orange-500">@{comment.replyingTo.username} </span>
              )}
              {comment.text}
            </p>
            <div className="flex items-center gap-0.5 shrink-0">
              <Button
                variant="ghost"
                size="icon"
                onClick={() => onVote(comment._id, "up")}
                aria-label="Upvote"
                disabled={isOwn}
                className={`h-7 w-7 cursor-pointer ${currentVote === "up" ? "text-green-800" : "text-muted-foreground hover:text-green-700"}`}
              >
                <ThumbsUp className="h-[15px] w-[15px]" />
              </Button>
              <span className={`text-[12px] font-semibold tabular-nums w-4 text-center ${comment.score > 0 ? "text-green-800" : comment.score < 0 ? "text-red-700" : "text-gray-600"}`}>
                {comment.score}
              </span>
              <Button
                variant="ghost"
                size="icon"
                onClick={() => onVote(comment._id, "down")}
                aria-label="Downvote"
                disabled={isOwn}
                className={`h-7 w-7 cursor-pointer ${currentVote === "down" ? "text-red-700" : "text-muted-foreground hover:text-red-600"}`}
              >
                <ThumbsDown className="h-[15px] w-[15px]" />
              </Button>
            </div>
          </div>

          <div className="flex items-center gap-3 mt-0 -mb-1">
            <p className="text-[12px] text-gray-400 leading-7">{timeAgo}</p>
            <button
              onClick={() => {
                setShowReplyForm(!showReplyForm);
                if (!showReplyForm) {
                  trackEvent("reply_form_open");
                  setReplyText("");
                }
              }}
              className="flex items-center gap-1 text-[12px] text-gray-400 hover:text-gray-600 cursor-pointer"
            >
              <MessageSquare className="h-[13px] w-[13px]" />
              Odgovori
            </button>
            <CommentReactions
              commentId={comment._id}
              reactions={comment.reactions ?? []}
              onReact={onReact}
              activeEmojis={comment.myReactions ?? []}
            />
          </div>

          {/* Inline reply form */}
          {showReplyForm && (
            <form onSubmit={handleReplySubmit} className="mt-2">
              {comment.parentId ? (
                <div className="mention-wrapper flex items-start rounded-md">
                  <span className="shrink-0 select-none text-sm font-semibold text-orange-500 pl-3 pt-2">
                    @{comment.username}
                  </span>
                  <Textarea
                    value={replyText}
                    onChange={(e) => setReplyText(e.target.value)}
                    placeholder="Napiši odgovor..."
                    maxLength={1000}
                    rows={2}
                    className="resize-none text-sm !border-0 !shadow-none"
                    disabled={posting}
                    autoFocus
                  />
                </div>
              ) : (
                <Textarea
                  value={replyText}
                  onChange={(e) => setReplyText(e.target.value)}
                  placeholder="Napiši odgovor..."
                  maxLength={1000}
                  rows={2}
                  className="resize-none text-sm"
                  disabled={posting}
                  autoFocus
                />
              )}
              <div className="flex justify-end gap-2 mt-1.5">
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  onClick={() => { setShowReplyForm(false); setReplyText(""); }}
                >
                  Otkaži
                </Button>
                <Button
                  type="submit"
                  disabled={!replyText.trim() || posting}
                  className="bg-orange-500 text-white hover:bg-orange-600"
                  size="sm"
                >
                  {posting ? "Slanje\u2026" : "Odgovori"}
                </Button>
              </div>
            </form>
          )}
        </div>
      </div>

      {/* Replies */}
      {(comment.replies ?? []).length > 0 && (
        <div className="ml-6 border-l-2 border-gray-100 pl-3">
          {(comment.replies ?? []).map((reply) => (
            <CommentItem
              key={reply._id}
              comment={reply}
              currentVotes={currentVotes}
              onVote={onVote}
              onReply={onReply}
              onReact={onReact}
              anonymousId={anonymousId}
            />
          ))}
        </div>
      )}
    </div>
  );
}
