import { useState } from "react";
import { ThumbsUp, ThumbsDown, MessageSquare, User } from "lucide-react";
import { Id } from "../../convex/_generated/dataModel";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { CommentReactions } from "./CommentReactions";
import { trackEvent } from "../utils/tracking";

export interface Comment {
  _id: Id<"comments">;
  text: string;
  score: number;
  createdAt: number;
  authorId: string;
  parentId?: Id<"comments">;
  replies?: Comment[];
  username: string;
  isAutoGenerated: boolean;
  reactions?: Array<{emoji: string; count: number}>;
  myReactions?: string[];
}

interface Props {
  comment: Comment;
  currentVotes: Record<string, "up" | "down">;
  onVote: (commentId: string, direction: "up" | "down") => void;
  onReply: (parentId: string, text: string) => Promise<void>;
  onReact: (targetType: "listing" | "comment", targetId: string, emoji: string, category: "price" | "general") => void;
  anonymousId: string;
  isReply?: boolean;
}

export function CommentItem({ comment, currentVotes, onVote, onReply, onReact, anonymousId, isReply }: Props) {
  const [showReplyForm, setShowReplyForm] = useState(false);
  const [replyText, setReplyText] = useState("");
  const [posting, setPosting] = useState(false);
  const timeAgo = formatTimeAgo(comment.createdAt);
  const isOwn = comment.authorId === anonymousId;
  const currentVote = currentVotes[comment._id] ?? null;

  async function handleReplySubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!replyText.trim()) return;
    setPosting(true);
    try {
      await onReply(comment._id, replyText);
      setReplyText("");
      setShowReplyForm(false);
    } finally {
      setPosting(false);
    }
  }

  return (
    <div>
      <div className="flex gap-3 py-3 border-b border-gray-100 last:border-0">
        {/* Avatar */}
        <div className="shrink-0 w-9 h-9 rounded-full bg-gray-100 flex items-center justify-center">
          <User className="h-[17px] w-[17px] text-gray-400" />
        </div>

        {/* Content */}
        <div className="flex-1 min-w-0">
          <p className={`text-[12px] font-medium mb-0.5 ${comment.isAutoGenerated ? "italic text-gray-400" : "text-gray-600"}`}>
            {comment.username}
          </p>
          <div className="flex justify-between items-center gap-2">
            <p className="text-[14px] text-gray-800 break-words leading-snug flex-1 min-w-0">{comment.text}</p>
            <div className="flex items-center gap-0.5 shrink-0">
              <Button
                variant="ghost"
                size="icon"
                onClick={() => onVote(comment._id, "up")}
                aria-label="Upvote"
                disabled={isOwn}
                className={`h-7 w-7 cursor-pointer ${currentVote === "up" ? "text-green-800" : "text-muted-foreground hover:text-green-700"}`}
              >
                <ThumbsUp className="h-[15px] w-[15px]" />
              </Button>
              <span className={`text-[12px] font-semibold tabular-nums w-4 text-center ${comment.score > 0 ? "text-green-800" : comment.score < 0 ? "text-red-700" : "text-gray-600"}`}>
                {comment.score}
              </span>
              <Button
                variant="ghost"
                size="icon"
                onClick={() => onVote(comment._id, "down")}
                aria-label="Downvote"
                disabled={isOwn}
                className={`h-7 w-7 cursor-pointer ${currentVote === "down" ? "text-red-700" : "text-muted-foreground hover:text-red-600"}`}
              >
                <ThumbsDown className="h-[15px] w-[15px]" />
              </Button>
            </div>
          </div>

          <div className="flex items-center gap-3 mt-0 -mb-1">
            <p className="text-[12px] text-gray-400 leading-7">{timeAgo}</p>
            {!isReply && (
              <button
                onClick={() => { setShowReplyForm(!showReplyForm); if (!showReplyForm) trackEvent("reply_form_open"); }}
                className="flex items-center gap-1 text-[12px] text-gray-400 hover:text-gray-600 cursor-pointer"
              >
                <MessageSquare className="h-[13px] w-[13px]" />
                Odgovori
              </button>
            )}
            <CommentReactions
              commentId={comment._id}
              reactions={comment.reactions ?? []}
              onReact={onReact}
              activeEmojis={comment.myReactions ?? []}
            />
          </div>

          {/* Inline reply form */}
          {showReplyForm && (
            <form onSubmit={handleReplySubmit} className="mt-2">
              <Textarea
                value={replyText}
                onChange={(e) => setReplyText(e.target.value)}
                placeholder="Napiši odgovor..."
                maxLength={1000}
                rows={2}
                className="resize-none text-sm"
                disabled={posting}
                autoFocus
              />
              <div className="flex justify-end gap-2 mt-1.5">
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  onClick={() => { setShowReplyForm(false); setReplyText(""); }}
                >
                  Otkaži
                </Button>
                <Button
                  type="submit"
                  disabled={!replyText.trim() || posting}
                  className="bg-orange-500 text-white hover:bg-orange-600"
                  size="sm"
                >
                  {posting ? "Slanje\u2026" : "Odgovori"}
                </Button>
              </div>
            </form>
          )}
        </div>
      </div>

      {/* Replies */}
      {(comment.replies ?? []).length > 0 && (
        <div className="ml-6 border-l-2 border-gray-100 pl-3">
          {(comment.replies ?? []).map((reply) => (
            <CommentItem
              key={reply._id}
              comment={reply}
              currentVotes={currentVotes}
              onVote={onVote}
              onReply={onReply}
              onReact={onReact}
              anonymousId={anonymousId}
              isReply
            />
          ))}
        </div>
      )}
    </div>
  );
}

function formatTimeAgo(timestamp: number): string {
  const diff = Date.now() - timestamp;
  const minutes = Math.floor(diff / 60_000);
  if (minutes < 1) return "upravo";
  if (minutes < 60) return `pre ${minutes} min`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `pre ${hours}h`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `pre ${days}d`;
  const weeks = Math.floor(days / 7);
  return `pre ${weeks}n`;
}
