import { useState, useEffect } from "react";
import { X, User } from "lucide-react";
import { createPortal } from "react-dom";
import { useShadowPortal } from "../context/shadow-portal";

interface ReadOnlyComment {
  _id: string;
  text: string;
  username: string;
  isAutoGenerated: boolean;
  createdAt: number;
  score: number;
  replies?: ReadOnlyComment[];
}

interface ListingData {
  title: string;
  price: string;
  imageUrl: string;
  url: string;
  isDeleted: boolean;
}

interface Props {
  listing: ListingData | null;
  comments: ReadOnlyComment[];
}

export function DeletedListingModal({ listing, comments }: Props) {
  const [dismissed, setDismissed] = useState(false);
  const portalTarget = useShadowPortal();

  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setDismissed(true);
    };
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, []);

  if (dismissed) return null;

  const modal = (
    <div
      style={{ position: "fixed", inset: 0, zIndex: 2147483646, pointerEvents: "auto" }}
      className="flex items-center justify-center bg-black/50"
      onClick={() => setDismissed(true)}
    >
      <div
        className="bg-white rounded-xl shadow-2xl w-full max-w-lg max-h-[80vh] flex flex-col mx-4"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-200 shrink-0">
          <div className="flex items-center gap-2">
            <span className="text-sm bg-red-100 text-red-600 px-2 py-1 rounded font-medium">
              Obrisan oglas
            </span>
          </div>
          <button
            onClick={() => setDismissed(true)}
            className="rounded-sm cursor-pointer opacity-70 hover:opacity-100"
            aria-label="Zatvori"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto">
          {listing ? (
            <>
              {/* Listing info card */}
              <div className="px-5 py-4 border-b border-gray-100">
                <div className="flex gap-3">
                  {listing.imageUrl && (
                    <img
                      src={listing.imageUrl}
                      alt=""
                      className="w-24 h-18 object-cover rounded shrink-0"
                    />
                  )}
                  <div className="min-w-0">
                    <p className="text-base font-semibold text-gray-800 leading-snug">
                      {listing.title}
                    </p>
                    <p className="text-lg text-orange-600 font-bold mt-1">
                      {listing.price}
                    </p>
                  </div>
                </div>
              </div>

              {/* Comments */}
              <div className="px-5 py-3">
                {comments.length === 0 ? (
                  <p className="text-sm text-gray-400 text-center py-6">
                    Nema komentara za ovaj oglas.
                  </p>
                ) : (
                  <div>
                    <p className="text-xs text-gray-500 font-medium mb-3">
                      Komentari ({comments.reduce((sum, c) => sum + 1 + (c.replies?.length ?? 0), 0)})
                    </p>
                    {comments.map((c) => (
                      <ReadOnlyCommentItem key={c._id} comment={c} />
                    ))}
                  </div>
                )}
              </div>
            </>
          ) : (
            <div className="px-5 py-10 text-center">
              <p className="text-sm text-gray-500">
                Ovaj oglas je obrisan. Nemamo sačuvane podatke o njemu.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );

  return portalTarget ? createPortal(modal, portalTarget) : modal;
}

function ReadOnlyCommentItem({ comment }: { comment: ReadOnlyComment }) {
  const timeAgo = formatTimeAgo(comment.createdAt);

  return (
    <div>
      <div className="flex gap-2.5 py-2.5 border-b border-gray-50 last:border-0">
        <div className="shrink-0 w-8 h-8 rounded-full bg-gray-100 flex items-center justify-center">
          <User className="h-3.5 w-3.5 text-gray-400" />
        </div>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2">
            <p className={`text-xs font-medium ${comment.isAutoGenerated ? "italic text-gray-400" : "text-gray-600"}`}>
              {comment.username}
            </p>
            <p className="text-xs text-gray-400">{timeAgo}</p>
          </div>
          <p className="text-sm text-gray-800 break-words leading-snug mt-0.5">
            {comment.text}
          </p>
        </div>
      </div>

      {/* Replies */}
      {(comment.replies ?? []).length > 0 && (
        <div className="ml-5 border-l-2 border-gray-100 pl-2.5">
          {(comment.replies ?? []).map((reply) => (
            <ReadOnlyCommentItem key={reply._id} comment={reply} />
          ))}
        </div>
      )}
    </div>
  );
}

function formatTimeAgo(timestamp: number): string {
  const diff = Date.now() - timestamp;
  const minutes = Math.floor(diff / 60_000);
  if (minutes < 1) return "upravo";
  if (minutes < 60) return `pre ${minutes} min`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `pre ${hours}h`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `pre ${days}d`;
  const weeks = Math.floor(days / 7);
  return `pre ${weeks}n`;
}
