import { useState, useEffect, useRef } from "react";
import { Comment, CommentItem } from "./CommentItem";
import { LatestComment, LatestFeedItem } from "./LatestFeedItem";
import { PostForm } from "./PostForm";
import { VinCheck } from "./VinCheck";
import { X, Bell, ChevronDown, LogOut } from "lucide-react";
import { trackEvent } from "../utils/tracking";
import { formatTimeAgo } from "../utils/formatTimeAgo";

type Tab = "listing" | "latest" | "notifications";

interface Props {
  listingId: string | null;
  comments: Comment[];
  commentCount: number;
  latestComments: LatestComment[];
  currentVotes: Record<string, "up" | "down">;
  onVote: (commentId: string, direction: "up" | "down") => void;
  onPost: (text: string) => Promise<void>;
  onReply: (parentId: string, text: string) => Promise<void>;
  onReact: (targetType: "listing" | "comment", targetId: string, emoji: string, category: "price" | "general") => void;
  error: string | null;
  onRetry: () => void;
  anonymousId: string;
  username: string;
  isAutoGenerated: boolean;
  onUsernameChange: (username: string, isAutoGenerated: boolean) => void;
  vin: string | null;
  boughtNewInSerbia: boolean;
  deletedListingData: { title: string; price: string; imageUrl: string; url: string; isDeleted: boolean } | null;
  auth: {
    user: import("../utils/auth").UserData | null;
    signingIn: boolean;
    signIn: () => Promise<void>;
    signOut: () => Promise<void>;
    updateDisplayName: (name: string) => Promise<void>;
    updateEmailNotifications: (enabled: boolean) => Promise<void>;
  };
  unreadCount: number;
  notifications: Array<{
    _id: import("../../convex/_generated/dataModel").Id<"notifications">;
    triggerAuthorName: string;
    listingId: string;
    listingUrl: string | null;
    read: boolean;
    createdAt: number;
    type: string;
  }>;
  onMarkAllRead: () => Promise<void>;
  onMarkRead: (notificationId: import("../../convex/_generated/dataModel").Id<"notifications">) => void;
}

const DRAWER_STATE_KEY = "paCommentsDrawerOpen";
const WHATS_NEW_KEY = "paWhatsNewDismissed_googleSignIn";

export function Drawer({
  listingId,
  comments,
  commentCount,
  latestComments,
  currentVotes,
  onVote,
  onPost,
  onReply,
  onReact,
  error,
  onRetry,
  anonymousId,
  username,
  isAutoGenerated,
  onUsernameChange,
  vin,
  boughtNewInSerbia,
  deletedListingData,
  auth,
  unreadCount,
  notifications,
  onMarkAllRead,
  onMarkRead,
}: Props) {
  const [open, setOpen] = useState(false);
  const [animating, setAnimating] = useState(false);
  const [activeTab, setActiveTab] = useState<Tab>(
    listingId ? "listing" : "latest"
  );
  const [showWhatsNew, setShowWhatsNew] = useState(
    () => !localStorage.getItem(WHATS_NEW_KEY)
  );
  const [showAccountMenu, setShowAccountMenu] = useState(false);
  const [editingName, setEditingName] = useState("");
  const [accountError, setAccountError] = useState<string | null>(null);
  const panelRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (localStorage.getItem(DRAWER_STATE_KEY) === "true") setOpen(true);
  }, []);

  function dismissWhatsNew() {
    setShowWhatsNew(false);
    localStorage.setItem(WHATS_NEW_KEY, "1");
    trackEvent("whatsnew_dismiss");
  }

  function toggle() {
    if (animating) return;
    const next = !open;
    setAnimating(true);
    setOpen(next);
    localStorage.setItem(DRAWER_STATE_KEY, String(next));
    trackEvent(next ? "drawer_open" : "drawer_close");
  }

  return (
    <div
      ref={panelRef}
      style={{
        position: "fixed",
        zIndex: 2147483647,
        top: 0,
        right: 0,
        height: "100dvh",
        width: "40%",
        transform: open ? "translateX(0)" : "translateX(100%)",
        transition: "transform 500ms ease-in-out",
      }}
      onTransitionEnd={() => setAnimating(false)}
    >
      {/* Toggle tab */}
      <button
        onClick={toggle}
        disabled={animating}
        style={{ position: "absolute", transform: "translateX(-100%) translateY(-50%)", boxShadow: "-4px 0 16px rgba(0, 0, 0, 0.12)" }}
        className="cursor-pointer left-0 top-1/2 flex flex-col items-center justify-center gap-1 bg-orange-500 text-white w-9 rounded-l-lg p-6 shadow-lg hover:bg-orange-600 disabled:opacity-80"
        aria-label="Toggle comments"
      >
        <span className="text-lg leading-none">💬</span>
        {listingId && commentCount > 0 && (
          <span className="text-[20px] font-bold leading-none">
            {commentCount > 99 ? "99+" : commentCount}
          </span>
        )}
        {unreadCount > 0 && (
          <span
            style={{ position: "absolute", top: 2, left: 2, minWidth: 18, height: 18, display: "flex", alignItems: "center", justifyContent: "center", padding: "0 4px" }}
            className="bg-red-500 rounded-full text-[10px] font-bold text-white leading-none border-2 border-white"
          >
            {unreadCount > 9 ? "9+" : unreadCount}
          </span>
        )}
      </button>

      {/* Drawer panel */}
      <div
        className="h-full bg-background flex flex-col"
        style={{ boxShadow: "-4px 0 16px rgba(0, 0, 0, 0.12)" }}
      >
        {/* Header */}
        <div className="px-5 py-3.5 border-b border-border shrink-0 flex items-center justify-between">
          <h2 className="text-[17px] font-semibold text-foreground tracking-[-0.01em]">
            {activeTab === "notifications" ? "Obaveštenja" : listingId ? "Komentari" : "Poslednji komentari"}
          </h2>
          <div className="flex items-center gap-1.5">
            {auth.user && (
              <button
                onClick={() => { setActiveTab(activeTab === "notifications" ? (listingId ? "listing" : "latest") : "notifications"); trackEvent("tab_switch", { tab: "notifications" }); }}
                className={`rounded-md cursor-pointer p-1.5 transition-colors relative ${
                  activeTab === "notifications" ? "text-orange-500 bg-orange-50" : "text-gray-400 hover:text-gray-600 hover:bg-gray-100"
                }`}
                aria-label="Obaveštenja"
              >
                <Bell className="h-[18px] w-[18px]" />
                {unreadCount > 0 && (
                  <span style={{ position: "absolute", top: -2, right: -2 }} className="bg-red-500 text-white text-[9px] rounded-full h-3.5 min-w-3.5 flex items-center justify-center px-0.5 leading-none font-medium">
                    {unreadCount > 99 ? "99+" : unreadCount}
                  </span>
                )}
              </button>
            )}
            <button
              onClick={toggle}
              disabled={animating}
              className="rounded-md cursor-pointer p-1.5 opacity-70 hover:opacity-100 hover:bg-gray-100 transition-colors"
              aria-label="Close"
            >
              <X className="h-[18px] w-[18px]" />
            </button>
          </div>
        </div>

        {/* Tabs — only listing/latest, no bell */}
        {listingId && activeTab !== "notifications" && (
          <div className="flex border-b border-border shrink-0">
            <button
              onClick={() => { setActiveTab("listing"); trackEvent("tab_switch", { tab: "listing" }); }}
              className={`flex-1 cursor-pointer text-[15px] py-2.5 font-medium transition-colors ${
                activeTab === "listing"
                  ? "text-orange-500 border-b-2 border-orange-500"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              Ovaj oglas
              {commentCount > 0 && (
                <span className="ml-1 text-muted-foreground font-normal">
                  ({commentCount})
                </span>
              )}
            </button>
            <button
              onClick={() => { setActiveTab("latest"); trackEvent("tab_switch", { tab: "latest" }); }}
              className={`flex-1 cursor-pointer text-[15px] py-2.5 font-medium transition-colors ${
                activeTab === "latest"
                  ? "text-orange-500 border-b-2 border-orange-500"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              Najnoviji
            </button>
          </div>
        )}

        {showWhatsNew && (
          <div className="px-4 py-2.5 bg-blue-50 border-b border-blue-200 shrink-0 flex items-start gap-2">
            <span className="text-[14px] leading-snug text-blue-700">
              <span className="font-semibold">Novo:</span> Prijavi se sa Google nalogom i dobijaj obaveštenja kada neko odgovori na tvoj komentar.
            </span>
            <button
              onClick={dismissWhatsNew}
              className="shrink-0 text-blue-400 hover:text-blue-600 cursor-pointer mt-0.5"
              aria-label="Dismiss"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        )}

        {/* Sign-in prompt (when not signed in) */}
        {!auth.user && (
          <div className="px-5 py-2.5 border-b border-border shrink-0">
            <button
              onClick={auth.signIn}
              disabled={auth.signingIn}
              className="w-full flex items-center justify-center gap-2 py-2 px-3 rounded-md text-[13px] text-gray-500 bg-gray-50 hover:bg-gray-100 transition-colors cursor-pointer border border-gray-200"
            >
              <svg className="h-4 w-4" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92a5.06 5.06 0 01-2.2 3.32v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.1z" fill="#4285F4"/>
                <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
                <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"/>
                <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
              </svg>
              {auth.signingIn ? "Prijavljivanje..." : "Prijavi se"}
            </button>
          </div>
        )}

        {/* Signed-in user bar */}
        {auth.user && activeTab !== "notifications" && (
          <div className="shrink-0">
            <button
              onClick={() => setShowAccountMenu(!showAccountMenu)}
              className="w-full px-5 py-2.5 flex items-center justify-between cursor-pointer hover:bg-gray-50/80 transition-colors border-b border-border"
            >
              <div className="flex items-center gap-2">
                <div className="h-6 w-6 rounded-full bg-orange-100 flex items-center justify-center">
                  <span className="text-[11px] font-semibold text-orange-600">
                    {auth.user.displayName.charAt(0).toUpperCase()}
                  </span>
                </div>
                <span className="text-[13px] font-medium text-gray-700">
                  {auth.user.displayName}
                </span>
                <span className="text-[10px] text-green-600">✓</span>
              </div>
              <ChevronDown className={`h-3.5 w-3.5 text-gray-400 transition-transform ${showAccountMenu ? "rotate-180" : ""}`} />
            </button>

            {/* Account menu dropdown */}
            {showAccountMenu && (
              <div className="px-5 py-3 border-b border-border bg-gray-50/60 space-y-3">
                <div>
                  <label className="text-[11px] font-medium text-gray-400 uppercase tracking-wider mb-1.5 block">Ime za prikaz</label>
                  <div className="flex gap-2">
                    <input
                      type="text"
                      value={editingName}
                      onChange={(e) => setEditingName(e.target.value)}
                      placeholder={auth.user.displayName}
                      maxLength={30}
                      className="flex-1 text-[13px] px-3 py-1.5 rounded-md bg-white text-gray-700 placeholder:text-gray-300"
                      style={{ border: "1px solid #e5e7eb" }}
                    />
                    <button
                      onClick={async () => {
                        if (editingName.trim()) {
                          try {
                            setAccountError(null);
                            await auth.updateDisplayName(editingName.trim());
                            setEditingName("");
                          } catch (e: any) {
                            setAccountError(e.message ?? "Greška pri čuvanju imena");
                          }
                        }
                      }}
                      disabled={!editingName.trim()}
                      className="text-[12px] font-medium px-3 py-1.5 rounded-md bg-orange-500 text-white hover:bg-orange-600 disabled:opacity-40 cursor-pointer transition-colors"
                    >
                      Sačuvaj
                    </button>
                  </div>
                </div>
                <div className="flex items-center justify-between py-0.5">
                  <span className="text-[13px] text-gray-600">Email obaveštenja</span>
                  <button
                    onClick={async () => {
                      try {
                        setAccountError(null);
                        await auth.updateEmailNotifications(!auth.user!.emailNotifications);
                      } catch (e: any) {
                        setAccountError(e.message ?? "Greška pri ažuriranju");
                      }
                    }}
                    style={{
                      position: "relative",
                      width: 36,
                      height: 20,
                      borderRadius: 10,
                      border: "none",
                      padding: 0,
                      cursor: "pointer",
                      backgroundColor: auth.user.emailNotifications ? "#f97316" : "#d1d5db",
                      transition: "background-color 200ms",
                    }}
                  >
                    <span
                      style={{
                        position: "absolute",
                        top: 2,
                        left: 2,
                        width: 16,
                        height: 16,
                        borderRadius: 8,
                        backgroundColor: "#fff",
                        boxShadow: "0 1px 2px rgba(0,0,0,0.1)",
                        transform: auth.user.emailNotifications ? "translateX(16px)" : "translateX(0)",
                        transition: "transform 200ms",
                      }}
                    />
                  </button>
                </div>
                {accountError && (
                  <p className="text-[11px] text-red-500">{accountError}</p>
                )}
                <div className="pt-1 border-t border-gray-200">
                  <button
                    onClick={async () => {
                      await auth.signOut();
                      setShowAccountMenu(false);
                    }}
                    className="flex items-center gap-1.5 text-[12px] text-gray-400 hover:text-red-500 cursor-pointer transition-colors"
                  >
                    <LogOut className="h-3 w-3" />
                    Odjavi se
                  </button>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Listing tab content */}
        {activeTab === "listing" && listingId && (
          <>
            <div className="shrink-0">
              {deletedListingData && (
                <div className="px-5 py-3 border-b border-border">
                  <span className="text-[11px] bg-red-100 text-red-600 px-1.5 py-0.5 rounded font-medium">
                    Obrisan oglas
                  </span>
                  <div className="flex gap-3 mt-2">
                    {deletedListingData.imageUrl && (
                      <img
                        src={deletedListingData.imageUrl}
                        alt=""
                        className="w-40 h-28 object-cover rounded shrink-0"
                      />
                    )}
                    <div className="min-w-0">
                      <p className="text-[14px] font-semibold text-foreground leading-snug">
                        {deletedListingData.title}
                      </p>
                      <p className="text-[15px] text-orange-600 font-bold mt-0.5">
                        {deletedListingData.price}
                      </p>
                    </div>
                  </div>
                </div>
              )}
              <PostForm
                onPost={onPost}
                username={username}
                isAutoGenerated={isAutoGenerated}
                onUsernameChange={onUsernameChange}
                isSignedIn={!!auth.user}
              />
              {vin && <VinCheck vin={vin} boughtNewInSerbia={boughtNewInSerbia} />}
            </div>

            <div className="flex-1 overflow-y-auto px-5">
              {error ? (
                <div className="flex flex-col items-center gap-2 py-10 text-center">
                  <p className="text-[14px] text-gray-500">{error}</p>
                  <button
                    onClick={() => { onRetry(); trackEvent("connection_retry"); }}
                    className="text-[14px] text-orange-500 hover:underline"
                  >
                    Pokreni ponovo
                  </button>
                </div>
              ) : comments.length === 0 ? (
                <p className="text-[14px] text-gray-400 text-center py-10">
                  Nema komentara još uvek. Napiši prvi!
                </p>
              ) : (
                comments.map((c) => (
                  <CommentItem
                    key={c._id}
                    comment={c}
                    currentVotes={currentVotes}
                    onVote={onVote}
                    onReply={onReply}
                    onReact={onReact}
                    anonymousId={anonymousId}
                  />
                ))
              )}
            </div>
          </>
        )}

        {/* Latest tab content */}
        {activeTab === "latest" && (
          <div className="flex-1 overflow-y-auto px-5">
            {latestComments.length === 0 ? (
              <p className="text-[14px] text-gray-400 text-center py-10">
                Nema komentara još uvek.
              </p>
            ) : (
              latestComments.map((c) => (
                <LatestFeedItem key={c._id} comment={c} />
              ))
            )}
          </div>
        )}

        {/* Notifications tab content */}
        {activeTab === "notifications" && auth.user && (
          <div className="flex-1 overflow-y-auto">
            {notifications.length > 0 && (
              <div className="px-5 py-2 border-b border-border flex items-center justify-between">
                <button
                  onClick={onMarkAllRead}
                  className="text-[12px] text-orange-500 hover:underline cursor-pointer"
                >
                  Označi sve kao pročitano
                </button>
              </div>
            )}
            {notifications.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-16 px-8">
                <Bell className="h-8 w-8 text-gray-200 mb-3" />
                <p className="text-[14px] text-gray-400 text-center">
                  Nema obaveštenja.
                </p>
                <p className="text-[12px] text-gray-300 text-center mt-1">
                  Ovde ćeš videti kada neko odgovori na tvoj komentar.
                </p>
              </div>
            ) : (
              notifications.map((n) => (
                <button
                  key={n._id}
                  onClick={() => {
                    if (!n.read) onMarkRead(n._id);
                    const url = n.listingUrl ?? `https://www.polovniautomobili.com/auto-oglasi/${n.listingId}`;
                    try {
                      const currentPath = window.location.pathname;
                      const targetPath = new URL(url).pathname;
                      if (currentPath === targetPath) {
                        window.location.reload();
                        return;
                      }
                    } catch {}
                    window.location.href = url;
                  }}
                  className={`w-full text-left px-5 py-3 border-b border-gray-100 cursor-pointer hover:bg-gray-50 transition-colors ${
                    !n.read ? "bg-orange-50/50" : ""
                  }`}
                >
                  <p className="text-[13px] text-gray-700">
                    <span className="font-medium">{n.triggerAuthorName}</span>
                    {" je odgovorio/la na tvoj komentar"}
                  </p>
                  <p className="text-[11px] text-gray-400 mt-0.5">
                    {formatTimeAgo(n.createdAt)}
                  </p>
                </button>
              ))
            )}
          </div>
        )}

        <div className="shrink-0 px-5 py-3 border-t border-border">
          <p className="text-[12px] text-muted-foreground/70 text-center leading-normal">
            Sviđa ti se? Podeli sa prijateljima, komentari su korisniji za sve! 🚗
          </p>
          <p className="text-[11px] text-muted-foreground/40 text-center mt-1">
            Nezavisan projekat. Nije povezan sa polovniautomobili.com.
          </p>
        </div>
      </div>
    </div>
  );
}
