import { useState, useEffect, useRef } from "react";
import { Comment, CommentItem } from "./CommentItem";
import { LatestComment, LatestFeedItem } from "./LatestFeedItem";
import { PostForm } from "./PostForm";
import { X } from "lucide-react";

type Tab = "listing" | "latest";

interface Props {
  listingId: string | null;
  comments: Comment[];
  commentCount: number;
  latestComments: LatestComment[];
  currentVotes: Record<string, "up" | "down">;
  onVote: (commentId: string, direction: "up" | "down") => void;
  onPost: (text: string) => Promise<void>;
  onReply: (parentId: string, text: string) => Promise<void>;
  error: string | null;
  onRetry: () => void;
  anonymousId: string;
  username: string;
  isAutoGenerated: boolean;
  onUsernameChange: (username: string, isAutoGenerated: boolean) => void;
}

const DRAWER_STATE_KEY = "paCommentsDrawerOpen";

export function Drawer({
  listingId,
  comments,
  commentCount,
  latestComments,
  currentVotes,
  onVote,
  onPost,
  onReply,
  error,
  onRetry,
  anonymousId,
  username,
  isAutoGenerated,
  onUsernameChange,
}: Props) {
  const [open, setOpen] = useState(false);
  const [animating, setAnimating] = useState(false);
  const [activeTab, setActiveTab] = useState<Tab>(
    listingId ? "listing" : "latest"
  );
  const panelRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (localStorage.getItem(DRAWER_STATE_KEY) === "true") setOpen(true);
  }, []);

  function toggle() {
    if (animating) return;
    const next = !open;
    setAnimating(true);
    setOpen(next);
    localStorage.setItem(DRAWER_STATE_KEY, String(next));
  }

  return (
    <div
      ref={panelRef}
      style={{
        position: "fixed",
        zIndex: 2147483647,
        top: 0,
        right: 0,
        height: "100dvh",
        width: "40%",
        transform: open ? "translateX(0)" : "translateX(100%)",
        transition: "transform 500ms ease-in-out",
      }}
      onTransitionEnd={() => setAnimating(false)}
    >
      {/* Toggle tab */}
      <button
        onClick={toggle}
        disabled={animating}
        style={{ transform: "translateX(-100%) translateY(-50%)", boxShadow: "-4px 0 16px rgba(0, 0, 0, 0.12)" }}
        className="absolute cursor-pointer left-0 top-1/2 flex flex-col items-center justify-center gap-1 bg-orange-500 text-white w-9 rounded-l-lg p-6 shadow-lg hover:bg-orange-600 disabled:opacity-80"
        aria-label="Toggle comments"

      >
        <span className="text-lg leading-none">💬</span>
        {listingId && commentCount > 0 && (
          <span className="text-[20px] font-bold leading-none">
            {commentCount > 99 ? "99+" : commentCount}
          </span>
        )}
      </button>

      {/* Drawer panel */}
      <div
        className="h-full bg-background flex flex-col"
        style={{ boxShadow: "-4px 0 16px rgba(0, 0, 0, 0.12)" }}
      >
        {/* Header */}
        <div className="px-4 py-3 border-b border-border shrink-0 flex items-center justify-between">
          <h2 className="text-sm font-semibold text-foreground">Komentari</h2>
          <button
            onClick={toggle}
            disabled={animating}
            className="rounded-sm opacity-70 hover:opacity-100"
            aria-label="Close"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Tabs */}
        {listingId && (
          <div className="flex border-b border-border shrink-0">
            <button
              onClick={() => setActiveTab("listing")}
              className={`flex-1 text-xs py-2 font-medium transition-colors ${
                activeTab === "listing"
                  ? "text-orange-500 border-b-2 border-orange-500"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              Ovaj oglas
              {commentCount > 0 && (
                <span className="ml-1 text-muted-foreground font-normal">
                  ({commentCount})
                </span>
              )}
            </button>
            <button
              onClick={() => setActiveTab("latest")}
              className={`flex-1 text-xs py-2 font-medium transition-colors ${
                activeTab === "latest"
                  ? "text-orange-500 border-b-2 border-orange-500"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              Najnoviji
            </button>
          </div>
        )}

        {/* Listing tab content */}
        {activeTab === "listing" && listingId && (
          <>
            <div className="shrink-0">
              <PostForm
                onPost={onPost}
                username={username}
                isAutoGenerated={isAutoGenerated}
                onUsernameChange={onUsernameChange}
              />
            </div>

            <div className="flex-1 overflow-y-auto px-3">
              {error ? (
                <div className="flex flex-col items-center gap-2 py-8 text-center">
                  <p className="text-sm text-gray-500">{error}</p>
                  <button
                    onClick={onRetry}
                    className="text-sm text-orange-500 hover:underline"
                  >
                    Pokreni ponovo
                  </button>
                </div>
              ) : comments.length === 0 ? (
                <p className="text-sm text-gray-400 text-center py-8">
                  Nema komentara još uvek. Napiši prvi!
                </p>
              ) : (
                comments.map((c) => (
                  <CommentItem
                    key={c._id}
                    comment={c}
                    currentVotes={currentVotes}
                    onVote={onVote}
                    onReply={onReply}
                    anonymousId={anonymousId}
                  />
                ))
              )}
            </div>
          </>
        )}

        {/* Latest tab content */}
        {activeTab === "latest" && (
          <div className="flex-1 overflow-y-auto px-3">
            {latestComments.length === 0 ? (
              <p className="text-sm text-gray-400 text-center py-8">
                Nema komentara još uvek.
              </p>
            ) : (
              latestComments.map((c) => (
                <LatestFeedItem key={c._id} comment={c} />
              ))
            )}
          </div>
        )}
      </div>
    </div>
  );
}
