import { useRef, useState, useEffect } from "react";
import { ExternalLink, User } from "lucide-react";

interface LatestReply {
  _id: string;
  text: string;
  username: string;
  isAutoGenerated: boolean;
  createdAt: number;
}

export interface LatestComment {
  _id: string;
  text: string;
  username: string;
  isAutoGenerated: boolean;
  createdAt: number;
  replies: LatestReply[];
  listing: {
    title: string;
    price: string;
    imageUrl: string;
    url: string;
    isDeleted: boolean;
  } | null;
}

interface Props {
  comment: LatestComment;
}

export function LatestFeedItem({ comment }: Props) {
  const [expanded, setExpanded] = useState(false);
  const timeAgo = formatTimeAgo(comment.createdAt);
  const isDeleted = comment.listing?.isDeleted ?? false;

  if (!comment.listing) {
    return (
      <div className="py-1.5 border-b border-gray-100 last:border-0">
        <div className="flex gap-2">
          <div className="shrink-0 w-6 h-6 rounded-full bg-gray-100 flex items-center justify-center">
            <User className="h-3 w-3 text-gray-400" />
          </div>
          <div className="min-w-0">
            <p
              className={`text-xs font-medium mb-0.5 ${comment.isAutoGenerated ? "italic text-gray-400" : "text-gray-600"}`}
            >
              {comment.username}
            </p>
            <p className="text-sm text-gray-800 break-words leading-snug">
              {comment.text}
            </p>
            <p className="text-xs text-gray-400 mt-1">{timeAgo}</p>
          </div>
        </div>
      </div>
    );
  }

  const textRef = useRef<HTMLParagraphElement>(null);
  const [isTruncated, setIsTruncated] = useState(false);

  useEffect(() => {
    const el = textRef.current;
    if (el) setIsTruncated(el.scrollWidth > el.clientWidth);
  }, [comment.text]);

  return (
    <div className="py-1.5 border-b border-gray-100 last:border-0">
      <div
        onClick={isTruncated || expanded ? () => setExpanded(!expanded) : undefined}
        className={`flex items-start gap-2 p-2 rounded-lg bg-gray-50 hover:bg-gray-100 transition-colors ${isTruncated || expanded ? "cursor-pointer" : ""}`}
      >
        {comment.listing.imageUrl && (
          <img
            src={comment.listing.imageUrl}
            alt=""
            className="w-16 h-12 object-cover rounded shrink-0"
          />
        )}
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-1.5">
            <p className="text-xs font-medium text-gray-800 truncate">
              {comment.listing.title}
            </p>
            <p className="text-xs text-orange-600 font-semibold shrink-0">
              {comment.listing.price}
            </p>
            {isDeleted && (
              <span className="text-[10px] bg-red-100 text-red-600 px-1.5 py-0.5 rounded font-medium shrink-0">
                Obrisan oglas
              </span>
            )}
          </div>
          <p
            ref={textRef}
            className={`text-sm text-gray-800 leading-snug mt-1.5 ${expanded ? "break-words whitespace-pre-wrap" : "truncate"}`}
          >
            <span className={`text-xs font-medium ${comment.isAutoGenerated ? "italic text-gray-400" : "text-gray-600"}`}>{comment.username}</span>
            {" "}
            {comment.text}
          </p>
          <div className="flex items-center gap-2 mt-0.5">
            <p className="text-xs text-gray-400">{timeAgo}</p>
            <a
              href={comment.listing.url}
              target="_top"
              onClick={(e) => e.stopPropagation()}
              className="text-xs text-orange-500 hover:text-orange-600 flex items-center gap-0.5 no-underline"
            >
              Poseti oglas
              <ExternalLink className="h-3 w-3" />
            </a>
          </div>
          {expanded && comment.replies.length > 0 && (
            <div className="mt-2 border-l-2 border-gray-200 pl-2.5 flex flex-col gap-1.5">
              {comment.replies.map((reply) => (
                <div key={reply._id}>
                  <p className="text-sm text-gray-800 break-words leading-snug">
                    <span className={`text-xs font-medium ${reply.isAutoGenerated ? "italic text-gray-400" : "text-gray-600"}`}>{reply.username}</span>
                    {" "}
                    {reply.text}
                  </p>
                  <p className="text-xs text-gray-400">{formatTimeAgo(reply.createdAt)}</p>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function formatTimeAgo(timestamp: number): string {
  const diff = Date.now() - timestamp;
  const minutes = Math.floor(diff / 60_000);
  if (minutes < 1) return "upravo";
  if (minutes < 60) return `pre ${minutes} min`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `pre ${hours}h`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `pre ${days}d`;
  const weeks = Math.floor(days / 7);
  return `pre ${weeks}n`;
}
