import { useState, useEffect, useRef } from "react";
import { MessageSquarePlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { trackEvent } from "../utils/tracking";

const PLACEHOLDERS = [
  "Ostavi komentar...",
  "Deluje solidno za te pare.",
  "Ima li neko iskustva sa ovim motorom?",
  "Kilometraža deluje sumnjivo...",
  "Slike izgledaju okej, ali bih proverio lično.",
];

interface Props {
  onPost: (text: string) => Promise<void>;
  username: string;
  isAutoGenerated: boolean;
  onUsernameChange: (username: string, isAutoGenerated: boolean) => void;
}

export function PostForm({ onPost, username, isAutoGenerated, onUsernameChange }: Props) {
  const [expanded, setExpanded] = useState(false);
  const [text, setText] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [posting, setPosting] = useState(false);
  const [placeholderIndex, setPlaceholderIndex] = useState(0);
  const [animState, setAnimState] = useState<"visible" | "exiting" | "entering">("visible");
  const timeoutRef = useRef<ReturnType<typeof setTimeout>>();

  useEffect(() => {
    if (text) return;

    const interval = setInterval(() => {
      setAnimState("exiting");

      timeoutRef.current = setTimeout(() => {
        setPlaceholderIndex((i) => (i + 1) % PLACEHOLDERS.length);
        setAnimState("entering");

        timeoutRef.current = setTimeout(() => {
          setAnimState("visible");
        }, 300);
      }, 450);
    }, 10000);

    return () => {
      clearInterval(interval);
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
    };
  }, [text]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!text.trim()) return;
    setPosting(true);
    setError(null);
    try {
      await onPost(text);
      setText("");
      setExpanded(false);
    } catch {
      setError("Greška pri slanju. Pokušaj ponovo.");
    } finally {
      setPosting(false);
    }
  }

  if (!expanded) {
    return (
      <div className="px-5 py-3 border-b border-border">
        <button
          onClick={() => { setExpanded(true); trackEvent("post_form_open"); }}
          className="w-full flex items-center justify-center gap-2 py-2 px-4 rounded-md text-[14px] font-medium text-orange-500 bg-orange-50 hover:bg-orange-100 transition-colors cursor-pointer border-solid border border-orange-200"
        >
          <MessageSquarePlus className="h-4 w-4" />
          Ostavi komentar
        </button>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="px-5 py-3.5 border-b border-border">
      <div className="mb-2">
        <label className="text-[12px] font-medium text-muted-foreground mb-1 block">Nadimak</label>
        <input
          type="text"
          value={isAutoGenerated ? "" : username}
          onChange={(e) => onUsernameChange(e.target.value || "", !e.target.value)}
          placeholder={isAutoGenerated ? username : "Unesite nadimak..."}
          maxLength={30}
          className="w-full text-sm px-3 py-2 rounded-md bg-transparent outline-none text-gray-700 placeholder:text-gray-300"
          style={{ border: "1px solid #d1d5db" }}
          disabled={posting}
        />
      </div>

      <label className="text-[12px] font-medium text-muted-foreground mb-1 block">Komentar</label>
      <div className="relative">
        <Textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          maxLength={1000}
          rows={3}
          className="resize-none text-sm text-gray-700"
          disabled={posting}
          autoFocus
        />
        {!text && (
          <span
            className="animated-placeholder"
            data-state={animState}
          >
            {PLACEHOLDERS[placeholderIndex]}
          </span>
        )}
      </div>
      {error && <p className="text-[13px] text-red-500 mt-1">{error}</p>}
      <div className="flex justify-between items-center mt-2">
        <span className="text-[12px] text-muted-foreground">{text.length}/1000</span>
        <div className="flex gap-2">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={() => { setExpanded(false); setText(""); setError(null); }}
            className="cursor-pointer"
          >
            Otkaži
          </Button>
          <Button
            type="submit"
            disabled={!text.trim() || posting}
            className="bg-orange-500 cursor-pointer text-white hover:bg-orange-600"
            size="sm"
          >
            {posting ? "Slanje\u2026" : "Postavi"}
          </Button>
        </div>
      </div>
    </form>
  );
}
