const CAR_BRANDS = [
  "Golf", "Punto", "Pezo", "Astra", "Jugo", "Stojadin", "Fica", "Yugo",
  "Clio", "Megane", "Octavia", "Fabia", "Polo", "Corsa", "Leon", "Ibiza",
  "Tipo", "Brava", "Uno", "Kadett", "Lada", "Niva", "Zastava", "Skala", "Koral",
];

export function generateRandomUsername(): string {
  const brand = CAR_BRANDS[Math.floor(Math.random() * CAR_BRANDS.length)];
  const num = Math.floor(Math.random() * 900 + 100); // 100-999
  return `${brand}${num}`;
}

const USERNAME_KEY = "paCommentsUsername";
const AUTO_GENERATED_KEY = "paCommentsUsernameAutoGenerated";

export interface StoredUsername {
  username: string;
  isAutoGenerated: boolean;
}

export async function getOrCreateUsername(): Promise<StoredUsername> {
  const result = await chrome.storage.local.get([USERNAME_KEY, AUTO_GENERATED_KEY]);
  if (result[USERNAME_KEY]) {
    return {
      username: result[USERNAME_KEY] as string,
      isAutoGenerated: result[AUTO_GENERATED_KEY] !== false,
    };
  }

  const username = generateRandomUsername();
  await chrome.storage.local.set({
    [USERNAME_KEY]: username,
    [AUTO_GENERATED_KEY]: true,
  });
  return { username, isAutoGenerated: true };
}

export async function saveUsername(username: string, isAutoGenerated: boolean): Promise<void> {
  await chrome.storage.local.set({
    [USERNAME_KEY]: username,
    [AUTO_GENERATED_KEY]: isAutoGenerated,
  });
}
