import { convexTest } from "convex-test";
import { expect, test } from "vitest";
import { api, internal } from "../convex/_generated/api";
import schema from "../convex/schema";

test("getComments returns empty array for unknown listing", async () => {
  const t = convexTest(schema);
  const comments = await t.query(api.comments.getComments, {
    listingId: "99999",
  });
  expect(comments).toEqual([]);
});

test("getComments returns comments for listing sorted by score desc", async () => {
  const t = convexTest(schema);

  await t.mutation(api.comments.postComment, {
    listingId: "12345",
    text: "First comment",
    authorId: "user-a",
    username: "Golf123",
    isAutoGenerated: true,
  });
  await t.mutation(api.comments.postComment, {
    listingId: "12345",
    text: "Second comment",
    authorId: "user-b",
    username: "Punto456",
    isAutoGenerated: true,
  });

  const comments = await t.query(api.comments.getComments, {
    listingId: "12345",
  });
  expect(comments).toHaveLength(2);
  expect(comments[0].text).toBeDefined();
  expect(comments[0].score).toBeDefined();
});

test("postComment rejects empty text", async () => {
  const t = convexTest(schema);
  await expect(
    t.mutation(api.comments.postComment, {
      listingId: "12345",
      text: "   ",
      authorId: "user-a",
      username: "Golf123",
      isAutoGenerated: true,
    })
  ).rejects.toThrow();
});

test("postComment trims whitespace from text", async () => {
  const t = convexTest(schema);
  await t.mutation(api.comments.postComment, {
    listingId: "12345",
    text: "  hello  ",
    authorId: "user-a",
    username: "Golf123",
    isAutoGenerated: true,
  });
  const comments = await t.query(api.comments.getComments, { listingId: "12345" });
  expect(comments[0].text).toBe("hello");
});

test("postComment rejects text over 1000 chars", async () => {
  const t = convexTest(schema);
  await expect(
    t.mutation(api.comments.postComment, {
      listingId: "12345",
      text: "a".repeat(1001),
      authorId: "user-a",
      username: "Golf123",
      isAutoGenerated: true,
    })
  ).rejects.toThrow();
});

test("getComments sorts by score descending", async () => {
  const t = convexTest(schema);

  const id1 = await t.mutation(api.comments.postComment, {
    listingId: "12345",
    text: "Low score comment",
    authorId: "user-a",
    username: "Golf123",
    isAutoGenerated: true,
  });
  const id2 = await t.mutation(api.comments.postComment, {
    listingId: "12345",
    text: "High score comment",
    authorId: "user-b",
    username: "Punto456",
    isAutoGenerated: true,
  });

  await t.mutation(api.votes.vote, { commentId: id2, voterId: "user-c", direction: "up" });
  await t.mutation(api.votes.vote, { commentId: id2, voterId: "user-d", direction: "up" });

  const comments = await t.query(api.comments.getComments, { listingId: "12345" });
  expect(comments[0].text).toBe("High score comment");
  expect(comments[0].score).toBe(2);
  expect(comments[1].text).toBe("Low score comment");
  expect(comments[1].score).toBe(0);
});

test("findListingsWithoutComments returns only listings with zero comments", async () => {
  const t = convexTest(schema);

  await t.mutation(api.comments.postComment, {
    listingId: "111",
    text: "Existing comment",
    authorId: "user-a",
    username: "Golf123",
    isAutoGenerated: true,
  });

  const result = await t.query(api.comments.findListingsWithoutComments, {
    listingIds: ["111", "222", "333"],
  });

  expect(result).toEqual(["222", "333"]);
});

test("postComment: can reply to a reply (deep nesting allowed)", async () => {
  const t = convexTest(schema);

  const rootId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Root comment",
    authorId: "user-a",
    username: "UserA",
    isAutoGenerated: false,
  });

  const replyId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Reply to root",
    authorId: "user-b",
    parentId: rootId,
    username: "UserB",
    isAutoGenerated: false,
  });

  // This should NOT throw — deep replies are allowed
  const deepReplyId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Reply to reply",
    authorId: "user-c",
    parentId: replyId,
    username: "UserC",
    isAutoGenerated: false,
  });

  expect(deepReplyId).toBeTruthy();
});

test("postComment: reply must belong to same listing as parent", async () => {
  const t = convexTest(schema);

  const rootId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Root",
    authorId: "user-a",
    username: "UserA",
    isAutoGenerated: false,
  });

  await expect(
    t.mutation(api.comments.postComment, {
      listingId: "DIFFERENT",
      text: "Cross-listing reply",
      authorId: "user-b",
      parentId: rootId,
      username: "UserB",
      isAutoGenerated: false,
    })
  ).rejects.toThrow("Parent belongs to different listing");
});

test("getComments: deep replies grouped under root with replyingTo metadata", async () => {
  const t = convexTest(schema);

  const rootId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Root",
    authorId: "user-a",
    username: "UserA",
    isAutoGenerated: false,
  });

  const replyId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Reply to root",
    authorId: "user-b",
    parentId: rootId,
    username: "UserB",
    isAutoGenerated: false,
  });

  await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Reply to reply",
    authorId: "user-c",
    parentId: replyId,
    username: "UserC",
    isAutoGenerated: false,
  });

  const comments = await t.query(api.comments.getComments, { listingId: "L1" });

  // Only 1 top-level comment
  expect(comments).toHaveLength(1);
  expect(comments[0].text).toBe("Root");

  // Both replies grouped flat under root, sorted chronologically
  expect(comments[0].replies).toHaveLength(2);
  expect(comments[0].replies[0].text).toBe("Reply to root");
  expect(comments[0].replies[1].text).toBe("Reply to reply");

  // First reply has no replyingTo (direct child of root)
  expect(comments[0].replies[0].replyingTo).toBeUndefined();

  // Second reply has replyingTo pointing to UserB
  expect(comments[0].replies[1].replyingTo).toEqual({
    username: "UserB",
    commentId: replyId,
  });
});

test("getComments: replies sorted chronologically (not by score)", async () => {
  const t = convexTest(schema);

  const rootId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Root",
    authorId: "user-a",
    username: "UserA",
    isAutoGenerated: false,
  });

  await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "First reply",
    authorId: "user-b",
    parentId: rootId,
    username: "UserB",
    isAutoGenerated: false,
  });

  await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Second reply",
    authorId: "user-c",
    parentId: rootId,
    username: "UserC",
    isAutoGenerated: false,
  });

  const comments = await t.query(api.comments.getComments, { listingId: "L1" });
  expect(comments[0].replies[0].text).toBe("First reply");
  expect(comments[0].replies[1].text).toBe("Second reply");
});

test("getLatestComments includes isDeleted flag from listing", async () => {
  const t = convexTest(schema);

  await t.mutation(api.comments.postComment, {
    listingId: "12345",
    text: "This listing will be deleted",
    authorId: "user-a",
    username: "TestUser",
    isAutoGenerated: false,
  });

  await t.mutation(api.listings.upsertListing, {
    listingId: "12345",
    title: "Opel Astra",
    price: "1.899 €",
    imageUrl: "https://example.com/img.jpg",
    url: "https://www.polovniautomobili.com/auto-oglasi/12345/opel-astra",
  });

  await t.mutation(api.listings.markListingDeleted, { listingId: "12345" });

  const latest = await t.query(api.comments.getLatestComments, {});
  const comment = latest.find((c: any) => c.text === "This listing will be deleted");
  expect(comment?.listing?.isDeleted).toBe(true);
});

test("postComment triggers notification for parent author", async () => {
  const t = convexTest(schema);

  const userId = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "parent@gmail.com",
    firstName: "Parent",
    anonymousId: "anon-parent",
  });

  const parentId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Parent",
    authorId: "anon-parent",
    username: "Parent",
    isAutoGenerated: false,
  });
  await t.mutation(internal.users.migrateAnonymousComments, {
    anonymousId: "anon-parent",
    userId,
  });

  await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Reply",
    authorId: "anon-other",
    parentId,
    username: "Other",
    isAutoGenerated: false,
  });

  const notifications = await t.query(api.notifications.getNotifications, { userId });
  expect(notifications).toHaveLength(1);
  expect(notifications[0].triggerAuthorName).toBe("Other");
});
