import { convexTest } from "convex-test";
import { expect, test } from "vitest";
import { api, internal } from "../convex/_generated/api";
import schema from "../convex/schema";

test("createNotificationsForReply creates notification for parent comment author", async () => {
  const t = convexTest(schema);

  const userId = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "parent@gmail.com",
    firstName: "Parent",
    anonymousId: "anon-parent",
  });

  const parentId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Parent comment",
    authorId: "anon-parent",
    username: "Parent",
    isAutoGenerated: false,
  });

  await t.mutation(internal.users.migrateAnonymousComments, {
    anonymousId: "anon-parent",
    userId,
  });

  const replyId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "A reply",
    authorId: "anon-other",
    parentId,
    username: "Other",
    isAutoGenerated: false,
  });

  await t.mutation(internal.notifications.createNotificationsForReply, {
    commentId: replyId,
    parentId,
    listingId: "L1",
    authorName: "Other",
    authorId: "anon-other",
  });

  const notifications = await t.query(api.notifications.getNotifications, {
    userId,
  });
  expect(notifications).toHaveLength(1);
  expect(notifications[0].triggerAuthorName).toBe("Other");
  expect(notifications[0].read).toBe(false);
});

test("createNotificationsForReply does not notify yourself", async () => {
  const t = convexTest(schema);

  const userId = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "self@gmail.com",
    firstName: "Self",
    anonymousId: "anon-self",
  });

  const parentId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "My comment",
    authorId: "anon-self",
    username: "Self",
    isAutoGenerated: false,
  });

  await t.mutation(internal.users.migrateAnonymousComments, {
    anonymousId: "anon-self",
    userId,
  });

  const replyId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Replying to myself",
    authorId: "anon-self",
    parentId,
    username: "Self",
    isAutoGenerated: false,
  });

  await t.mutation(internal.notifications.createNotificationsForReply, {
    commentId: replyId,
    parentId,
    listingId: "L1",
    authorName: "Self",
    authorId: "anon-self",
  });

  const notifications = await t.query(api.notifications.getNotifications, {
    userId,
  });
  expect(notifications).toHaveLength(0);
});

test("createNotificationsForReply notifies root author for deep reply", async () => {
  const t = convexTest(schema);

  const rootUserId = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-root",
    email: "root@gmail.com",
    firstName: "Root",
    anonymousId: "anon-root",
  });

  const rootId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Root comment",
    authorId: "anon-root",
    username: "Root",
    isAutoGenerated: false,
  });

  await t.mutation(internal.users.migrateAnonymousComments, {
    anonymousId: "anon-root",
    userId: rootUserId,
  });

  const middleId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Middle reply",
    authorId: "anon-middle",
    parentId: rootId,
    username: "Middle",
    isAutoGenerated: false,
  });

  const deepId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Deep reply",
    authorId: "anon-deep",
    parentId: middleId,
    username: "Deep",
    isAutoGenerated: false,
  });

  await t.mutation(internal.notifications.createNotificationsForReply, {
    commentId: deepId,
    parentId: middleId,
    listingId: "L1",
    authorName: "Deep",
    authorId: "anon-deep",
  });

  const notifications = await t.query(api.notifications.getNotifications, {
    userId: rootUserId,
  });
  expect(notifications).toHaveLength(1);
});

test("deduplicates when parent author and root author are same user", async () => {
  const t = convexTest(schema);

  const userId = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "user@gmail.com",
    firstName: "User",
    anonymousId: "anon-user",
  });

  const rootId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Root",
    authorId: "anon-user",
    username: "User",
    isAutoGenerated: false,
  });

  await t.mutation(internal.users.migrateAnonymousComments, {
    anonymousId: "anon-user",
    userId,
  });

  const replyId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Reply",
    authorId: "anon-other",
    parentId: rootId,
    username: "Other",
    isAutoGenerated: false,
  });

  await t.mutation(internal.notifications.createNotificationsForReply, {
    commentId: replyId,
    parentId: rootId,
    listingId: "L1",
    authorName: "Other",
    authorId: "anon-other",
  });

  const notifications = await t.query(api.notifications.getNotifications, {
    userId,
  });
  expect(notifications).toHaveLength(1);
});

test("getUnreadCount returns correct count", async () => {
  const t = convexTest(schema);

  const userId = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "user@gmail.com",
    firstName: "User",
    anonymousId: "anon-user",
  });

  const rootId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Root",
    authorId: "anon-user",
    username: "User",
    isAutoGenerated: false,
  });

  await t.mutation(internal.users.migrateAnonymousComments, {
    anonymousId: "anon-user",
    userId,
  });

  for (const name of ["A", "B"]) {
    const replyId = await t.mutation(api.comments.postComment, {
      listingId: "L1",
      text: `Reply from ${name}`,
      authorId: `anon-${name}`,
      parentId: rootId,
      username: name,
      isAutoGenerated: false,
    });

    await t.mutation(internal.notifications.createNotificationsForReply, {
      commentId: replyId,
      parentId: rootId,
      listingId: "L1",
      authorName: name,
      authorId: `anon-${name}`,
    });
  }

  const count = await t.query(api.notifications.getUnreadCount, { userId });
  expect(count).toBe(2);
});

test("markAllRead marks all notifications as read", async () => {
  const t = convexTest(schema);

  const userId = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "user@gmail.com",
    firstName: "User",
    anonymousId: "anon-user",
  });

  const rootId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Root",
    authorId: "anon-user",
    username: "User",
    isAutoGenerated: false,
  });

  await t.mutation(internal.users.migrateAnonymousComments, {
    anonymousId: "anon-user",
    userId,
  });

  const replyId = await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Reply",
    authorId: "anon-other",
    parentId: rootId,
    username: "Other",
    isAutoGenerated: false,
  });

  await t.mutation(internal.notifications.createNotificationsForReply, {
    commentId: replyId,
    parentId: rootId,
    listingId: "L1",
    authorName: "Other",
    authorId: "anon-other",
  });

  await t.mutation(api.notifications.markAllRead, { userId });
  const count = await t.query(api.notifications.getUnreadCount, { userId });
  expect(count).toBe(0);
});
