import { convexTest } from "convex-test";
import { expect, test } from "vitest";
import { api } from "../convex/_generated/api";
import schema from "../convex/schema";

test("react: creates a new reaction", async () => {
  const t = convexTest(schema);
  await t.mutation(api.reactions.react, {
    targetType: "listing",
    targetId: "12345",
    reactorId: "user-a",
    emoji: "\u{1F60D}",
    category: "general",
  });

  const reactions = await t.query(api.reactions.getListingReactions, {
    listingId: "12345",
  });
  expect(reactions).toHaveLength(1);
  expect(reactions[0].emoji).toBe("\u{1F60D}");
});

test("react: toggling same emoji removes it", async () => {
  const t = convexTest(schema);
  await t.mutation(api.reactions.react, {
    targetType: "listing",
    targetId: "12345",
    reactorId: "user-a",
    emoji: "\u{1F60D}",
    category: "general",
  });
  await t.mutation(api.reactions.react, {
    targetType: "listing",
    targetId: "12345",
    reactorId: "user-a",
    emoji: "\u{1F60D}",
    category: "general",
  });

  const reactions = await t.query(api.reactions.getListingReactions, {
    listingId: "12345",
  });
  expect(reactions).toHaveLength(0);
});

test("react: price votes are mutually exclusive (switching removes old)", async () => {
  const t = convexTest(schema);
  await t.mutation(api.reactions.react, {
    targetType: "listing",
    targetId: "12345",
    reactorId: "user-a",
    emoji: "\u{1F44D}",
    category: "price",
  });
  await t.mutation(api.reactions.react, {
    targetType: "listing",
    targetId: "12345",
    reactorId: "user-a",
    emoji: "\u{1F44E}",
    category: "price",
  });

  const reactions = await t.query(api.reactions.getListingReactions, {
    listingId: "12345",
  });
  const priceReactions = reactions.filter((r: any) => r.category === "price");
  expect(priceReactions).toHaveLength(1);
  expect(priceReactions[0].emoji).toBe("\u{1F44E}");
});

test("react: user can have multiple different general reactions", async () => {
  const t = convexTest(schema);
  await t.mutation(api.reactions.react, {
    targetType: "listing",
    targetId: "12345",
    reactorId: "user-a",
    emoji: "\u{1F60D}",
    category: "general",
  });
  await t.mutation(api.reactions.react, {
    targetType: "listing",
    targetId: "12345",
    reactorId: "user-a",
    emoji: "\u26A0\uFE0F",
    category: "general",
  });

  const reactions = await t.query(api.reactions.getListingReactions, {
    listingId: "12345",
  });
  expect(reactions).toHaveLength(2);
});

test("react: comment reactions work and appear in getComments", async () => {
  const t = convexTest(schema);
  const commentId = await t.mutation(api.comments.postComment, {
    listingId: "12345",
    text: "Test comment",
    authorId: "author",
    username: "Golf123",
    isAutoGenerated: true,
  });

  await t.mutation(api.reactions.react, {
    targetType: "comment",
    targetId: commentId,
    reactorId: "user-a",
    emoji: "\u{1F604}",
    category: "general",
  });
  await t.mutation(api.reactions.react, {
    targetType: "comment",
    targetId: commentId,
    reactorId: "user-b",
    emoji: "\u{1F604}",
    category: "general",
  });

  const comments = await t.query(api.comments.getComments, {
    listingId: "12345",
    reactorId: "user-a",
  });
  expect(comments[0].reactions).toBeDefined();
  const laughReaction = comments[0].reactions.find((r: any) => r.emoji === "\u{1F604}");
  expect(laughReaction).toBeDefined();
  expect(laughReaction!.count).toBe(2);
  expect(comments[0].myReactions).toContain("\u{1F604}");
});
