import { convexTest } from "convex-test";
import { expect, test } from "vitest";
import { api, internal } from "../convex/_generated/api";
import schema from "../convex/schema";

test("createOrUpdateUser creates user with correct fields", async () => {
  const t = convexTest(schema);
  const { userId, sessionToken } = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "test@gmail.com",
    firstName: "Test",
    anonymousId: "anon-123",
  });
  expect(userId).toBeTruthy();
  const user = await t.query(api.users.getUser, { userId, sessionToken });
  expect(user).not.toBeNull();
  expect(user!.displayName).toBe("Test");
  expect(user!.isCustomName).toBe(false);
  expect(user!.emailNotifications).toBe(true);
});

test("createOrUpdateUser returns existing user on second call", async () => {
  const t = convexTest(schema);
  const result1 = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "test@gmail.com",
    firstName: "Test",
    anonymousId: "anon-123",
  });
  const result2 = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "test@gmail.com",
    firstName: "Test",
    anonymousId: "anon-123",
  });
  expect(result1.userId).toBe(result2.userId);
});

test("createOrUpdateUser updates email and firstName for returning users", async () => {
  const t = convexTest(schema);
  await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "old@gmail.com",
    firstName: "OldName",
    anonymousId: "anon-123",
  });
  const { userId, sessionToken } = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "new@gmail.com",
    firstName: "NewName",
    anonymousId: "anon-123",
  });
  const internal_user = await t.query(internal.users.getUserInternal, { userId });
  expect(internal_user!.email).toBe("new@gmail.com");
  expect(internal_user!.firstName).toBe("NewName");
});

test("migrateAnonymousComments backfills userId on matching comments", async () => {
  const t = convexTest(schema);
  await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "My comment",
    authorId: "anon-456",
    username: "Polo789",
    isAutoGenerated: true,
  });
  const { userId } = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-xyz",
    email: "user@gmail.com",
    firstName: "User",
    anonymousId: "anon-456",
  });
  await t.mutation(internal.users.migrateAnonymousComments, {
    anonymousId: "anon-456",
    userId,
  });
  const comments = await t.query(api.comments.getComments, { listingId: "L1" });
  expect(comments[0].userId).toBe(userId);
});

test("migrateAnonymousComments does not touch other users' comments", async () => {
  const t = convexTest(schema);
  await t.mutation(api.comments.postComment, {
    listingId: "L1",
    text: "Other user comment",
    authorId: "anon-OTHER",
    username: "Yugo100",
    isAutoGenerated: true,
  });
  const { userId } = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-xyz",
    email: "user@gmail.com",
    firstName: "User",
    anonymousId: "anon-456",
  });
  await t.mutation(internal.users.migrateAnonymousComments, {
    anonymousId: "anon-456",
    userId,
  });
  const comments = await t.query(api.comments.getComments, { listingId: "L1" });
  expect(comments[0].userId).toBeUndefined();
});

test("updateDisplayName changes user display name", async () => {
  const t = convexTest(schema);
  const { userId, sessionToken } = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "test@gmail.com",
    firstName: "Test",
    anonymousId: "anon-123",
  });
  await t.mutation(api.users.updateDisplayName, { userId, sessionToken, displayName: "CoolGuy" });
  const user = await t.query(api.users.getUser, { userId, sessionToken });
  expect(user!.displayName).toBe("CoolGuy");
  expect(user!.isCustomName).toBe(true);
});

test("updateDisplayName rejects empty name", async () => {
  const t = convexTest(schema);
  const { userId, sessionToken } = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "test@gmail.com",
    firstName: "Test",
    anonymousId: "anon-123",
  });
  await expect(
    t.mutation(api.users.updateDisplayName, { userId, sessionToken, displayName: "   " })
  ).rejects.toThrow();
});

test("updateDisplayName rejects name over 30 chars", async () => {
  const t = convexTest(schema);
  const { userId, sessionToken } = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "test@gmail.com",
    firstName: "Test",
    anonymousId: "anon-123",
  });
  await expect(
    t.mutation(api.users.updateDisplayName, { userId, sessionToken, displayName: "a".repeat(31) })
  ).rejects.toThrow();
});

test("updateDisplayName rejects control characters", async () => {
  const t = convexTest(schema);
  const { userId, sessionToken } = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "test@gmail.com",
    firstName: "Test",
    anonymousId: "anon-123",
  });
  await expect(
    t.mutation(api.users.updateDisplayName, { userId, sessionToken, displayName: "\u200F\u202E" })
  ).rejects.toThrow("Display name cannot be empty");
});

test("updateDisplayName rejects invalid session", async () => {
  const t = convexTest(schema);
  const { userId } = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "test@gmail.com",
    firstName: "Test",
    anonymousId: "anon-123",
  });
  await expect(
    t.mutation(api.users.updateDisplayName, { userId, sessionToken: "wrong-token", displayName: "Hacker" })
  ).rejects.toThrow("Invalid session");
});

test("updateEmailNotifications toggles email preference", async () => {
  const t = convexTest(schema);
  const { userId, sessionToken } = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "test@gmail.com",
    firstName: "Test",
    anonymousId: "anon-123",
  });
  await t.mutation(api.users.updateEmailNotifications, { userId, sessionToken, enabled: false });
  const user = await t.query(api.users.getUser, { userId, sessionToken });
  expect(user!.emailNotifications).toBe(false);
});

test("getUser returns null for invalid session token", async () => {
  const t = convexTest(schema);
  const { userId } = await t.mutation(internal.users.createOrUpdateUser, {
    googleId: "google-abc",
    email: "test@gmail.com",
    firstName: "Test",
    anonymousId: "anon-123",
  });
  const user = await t.query(api.users.getUser, { userId, sessionToken: "wrong-token" });
  expect(user).toBeNull();
});
